### ISSUE TITLE
Let the queue creator know when the queue has finished

### ISSUE THREAD

**Issue by baabaablackgoat** [baabaablackgoat/stalnks#28]

**Comment by CptSpaceToaster** [comment]
> Thank you so much for sharing your turnip prices with everyone! It looks like the queue you started has come to an end. If you would like, you can:
> 1. Leave everything as it is, and let folks come and go in a free-for-all fashion (consider sharing the code with friends or in a text channel)
> 2. Close your island and generate a **new** Dodo Code to get a sense of privacy again, and distribute it among friends or in a text channel, or start a new queue if a lot of folks are still asking.
> 3. Close your island and let us know you're done!
> 
> STONKS 📈
